### ISSUE TITLE
Listar hosts online

### ISSUE THREAD

**Issue by CordLab** [ElielCesar/Automacoes_Laboratorios#1]
Por gentileza criar um script para listar os host online e que respondem a solicitações do wsman para que o administrador saiba em quais deles os comandos serão executados.

**Comment by ElielCesar** [comment]
@CordLab resolvido, segue a hash 3683724

**Comment by ElielCesar** [comment]
> 
> 
> Por gentileza criar um script para listar os host online e que respondem a solicitações do wsman para que o administrador saiba em quais deles os comandos serão executados.
